title: Computer Vision Lab
email: manuelocc@gmail.com
author: Manuel Carita
logo: /static/img/logo.png
about: Manuel Carita
description: > 
  A Robotics, Computer Vision and Machine Learning lab by Manuel Carita. The main focus of the blog is Self-Driving Car Technology and Deep Learning.
baseurl: ""
url: "https://manul30.github.io" # the base hostname & protocol 
twitter_username: manuelocc30
github:  manul30

allowsearch: false
enableTags:  false

google_analytics: UA-104440412-1

paginate: 10
per_page: 10
paginate_path: "/blog/page:num/"
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-gist
  
exclude:
  - Gemfile
  - Gemfile.lock
