title: Computer Vision Lab
email: manuelocc@gmail.com
author: Manuel Carita
logo: /static/img/logo.png
about: Manuel Carita
description: > 
  Hi there! This is a site where I can share some description about some interest projects throught my career. The main topics related are Computer Vision, Robotics, Machine Learning and EVs.
baseurl: ""
url: "https://manul30.github.io" # the base hostname & protocol 
twitter_username: manuelocc30
github:  manul30

allowsearch: false
enableTags:  false

google_analytics: UA-104440412-1

paginate: 10
per_page: 10
paginate_path: "/blog/page:num/"
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-gist
  
exclude:
  - Gemfile
  - Gemfile.lock
